name: 'Snapcraft Build'
description: 'Build a Snapcraft project'
author: 'James Henstridge'
inputs:
  path:
    description: 'The location of the Snapcraft project.  Defaults to the base of the repository'
    default: '.'
runs:
  using: 'node12'
  main: 'dist/index.js'
